### PR TITLE
fix: for missing page titles in library spec pages

### LINKED ISSUE #6999: Library spec pages are missing page titles in the header
## Description
$subject
e.g. :- https://ballerina.io/spec/cache/

### PR DESCRIPTION
**Pull request by s-vamshi**
## Checklist

- [ ] **Page addition**
  - [ ] Add `permalink` to pages.

- [ ] **Page removal**
  - [ ] Remove entry from corresponding left nav YAML file.
  - [ ] Add `redirect_from` on the alternative page.
  - [ ] If no alternative page, add redirection on the `redirections.js ` file.

- [ ] **Page rename**
  - [ ] Add front-matter `redirect_from`.
  - [ ] Add front-matter `redirect_to:` (if applicable).

- [ ] **Page restrcuture**
  - [ ] Add `permalink` to pages.
  - [ ] Add front-matter `redirect_from`.
  - [ ] Add front-matter `redirect_to:` (if applicable).

### CODE REVIEW

File: pages/spec/[slug].js [hunk 1]
```diff
@@ -118,17 +118,21 @@ export default function PostPage({ frontmatter, content, codeSnippets }) {
...
         <meta name="description" content={frontmatter.description} />
         <meta name="keywords" content={frontmatter.keywords} />
 
-        <title>{frontmatter.title}</title>
+        <title>{frontmatter.title || extractLibraryNameFromContent()}</title>
 
         {/* <!--FB--> */}
         <meta property="og:type" content="article" />
-        <meta property="og:title" content={`Ballerina - ${frontmatter.title}`} />
+        <meta property="og:title" content={`Ballerina - ${frontmatter.title  || extractLibraryNameFromContent()}`} />
```
Comment (sm1990) [inline pages/spec/[slug].js:135]: Can you add 
<meta name="twitter:title" content={`Ballerina - ${frontmatter.title  || extractLibraryNameFromContent()}`} />
for twitter as well

**Comment by s-vamshi** [comment]
@sm1990 Can you please review now?

**Review by sm1990 — APPROVED** [review]
